# Generated by Django 4.2.3 on 2023-08-03 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0009_education"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
